### ISSUE TITLE
ProtoPNet vs BRAIxProtoPNet++

### ISSUE THREAD

**Issue by BanafshehKarimian** [ShreyasiPathak/prototype-based-breast-cancer-prediction#1]
Hi, I see no difference between the code of ProtoPNet and BRAIxProtoPNet++.

**Comment by ShreyasiPathak** [comment]
Hi! There's quite some difference between ProtoPNet and BRAIxProtoPNet++ code. Some examples below:
 
| File | Difference between ProtoPNet and BRAIxProtoPNet++ implementation|
| --- | --- | 
| model.py | prototype layer in Proto and both prototype layer and classification layer in BRAIxProtoPNet++ |
| train_and_test.py |  separation loss without margin in ProtoPNet and knowledge distillation loss, hinge loss added to separation loss in BRAIxProtoPNet++ |
| main.py | different training scheme |
| push.py vs push_braixx.py | prototype diversity in BRAIxProtoPNet++ |
